### ISSUE TITLE
Icon not updating

### ISSUE THREAD

**Issue by txgruppi** [tadeuzagallo/GithubPulse#1]
When I click on the reload button at the bottom-left corner and the commits go from 0 to 1 the icon is not updated, it stays red.

**Comment by tadeuzagallo** [comment]
Can you please check which version you're using? It was fixed on [fa863de](https://github.com/tadeuzagallo/GithubPulse/commit/fa863deedd348baf776ea6281a0302c3aa76f69a) and released on v0.2.1

**Comment by txgruppi** [comment]
I have no idea, is there a way to see the version? I will update here.

**Comment by tadeuzagallo** [comment]
You can just find the app on finder quick look it and it'll show the version.
