### ISSUE TITLE
Beeminder integration

### ISSUE THREAD

**Issue by kmarekspartz** [tadeuzagallo/GithubPulse#10]
https://www.beeminder.com/gitminder/

http://blog.beeminder.com/gitminder/

**Comment by tadeuzagallo** [comment]
Hey, thanks for the idea!

But I think both apps have the same goal actually, what kind of integration did you think?

**Comment by kmarekspartz** [comment]
It would be nice to send an alert when getting too close to derailing in beeminder, along with what the user would be charged.

**Comment by rafaell-lycan** [comment]
+1
