### ISSUE TITLE
Layout is messed up with too many commits in graph

### ISSUE THREAD

**Issue by ljharb** [tadeuzagallo/GithubPulse#11]
Try putting in my username - because I have a couple particularly high-commit days, the graph seems to flow outside the region, and the dropdown from the menubar becomes scrollable.

**Comment by tadeuzagallo** [comment]
Humm... I don't see it here...
![Here's what I see](https://cloud.githubusercontent.com/assets/764414/5732580/62679a9e-9b7b-11e4-89d7-902cdbf07f6b.png)
Can you attach a screenshot too? Also, you can try right click on the Github Pulse icon, it should refresh the WebView, so we can know if it's going to keep constantly happening or just happens sometimes...

**Comment by ljharb** [comment]
![screen shot 2015-01-13 at 5 30 00 pm](https://cloud.githubusercontent.com/assets/45469/5732615/d49e8154-9b49-11e4-90e3-78efe133dcb0.png)

Right-clicking definitely fixed it, thanks!

I think it happened because I'd clicked it when I had 0 commits, and then I pushed 2, and clicked it again, and then it was messed up? Also perhaps the retina screen?

**Comment by tadeuzagallo** [comment]
Humm, I see, but It shouldn't happen, I've done it before a lot of times during testing...
Looks like the size of the graph went mad, but makes no sense, because it's never updated.
Anyway I'll leave this open and look deeper into it as soon as I've finished the chrome extension to(day|morrow).

**Comment by tadeuzagallo** [comment]
I'm closing it here and tracking it on #18.
