### ISSUE TITLE
Layout break

### ISSUE THREAD

**Issue by rafaelstz** [tadeuzagallo/GithubPulse#15]
When the name is large breaking the layout.
![captura-de-tela-2015-01-14-as-13 43 38](https://cloud.githubusercontent.com/assets/610598/5741834/fcf5cd78-9bf4-11e4-8117-a4f5e9193c0f.png)

**Comment by tadeuzagallo** [comment]
Thanks for reporting!
It was fixed on #12, just hasn't been released yet...
