### ISSUE TITLE
Create a github.io page of project.

### ISSUE THREAD

**Issue by rafaell-lycan** [tadeuzagallo/GithubPulse#16]
Create a github.io page of project to divulge on a page.

We can use Jekyll or simple HTML for now.

**Comment by rafaell-lycan** [comment]
Maybe @wjp2013 can help-me =)

**Comment by tadeuzagallo** [comment]
I was going to suggest right that after finishing updating the layout!

If you feel like sparing some time, your help would be much appreciated! :+1:

**Comment by rafaell-lycan** [comment]
Nice =)

**Comment by oscarmcm** [comment]
I can help if anyone need @rafaell-lycan @tadeuzagallo

**Comment by rafaell-lycan** [comment]
@oscarmcm I created a basic structure with [Jekyll](http://jekyllrb.com/). I don't know if this is to much, but for now it's ok.

I keep drawing a layout in Photoshop and I will put here this weekend.

If you want to help, maybe tomorrow we can do it.

**Comment by oscarmcm** [comment]
@rafaell-lycan Yeah, jekyll is a good option, but we can use Pelican or simple html, I think that Jekyll is more useful if you want to build a blog with github, but it is still a good choice :smile: 

I'm using Jekyll in some other projects  where I Collaborate, so... lets go, make the things happen.

Perfect, I'm waiting tomorrow :+1:

**Comment by tadeuzagallo** [comment]
That looks promising! Thank you guys! :+1:

**Comment by rafaell-lycan** [comment]
No problem @tadeuzagallo, just pay us a beer (and bacon) after that :P

**Comment by GiaoGiaoCat** [comment]
:laughing: In fact, i am a ruby programmer not a designer.

Tks @oscarmcm @rafaell-lycan :+1:

**Comment by rafaell-lycan** [comment]
@tadeuzagallo , I think in something like this.

What you think? It's simple I know, but I want a feedback.

![github-pulse](https://cloud.githubusercontent.com/assets/1516450/5788724/48bd8e90-9e2e-11e4-858d-cca0817561cb.jpg)

**Comment by tadeuzagallo** [comment]
Nice! just missing the icon on the "What is Github Pulse?" section.
If you need any artwork it is in the `resources` folder, and the fonts are inside `javascript/fonts`.
Thanks again for the help! :smiley:

**Comment by oscarmcm** [comment]
Amazing! Nice and clean @rafaell-lycan I will make a basic setup of Jekyll project in my local computer using 
- Bower for packages
- Grunt for automated task
- Yeoman for generators

and after all we can develop the site, in a easy(sh) mode 

Btw I think that this is the most simple structure:
- Sass or Vanilla CSS
- Vanilla JavaScript instead of CoffeeScript
- Vendor CSS with autoprefixer
- HTML5 Boilerplate for templates instead of Jekyll Template Engine

If you dont have any problems with this setup, lets do it, or if you have any suggestion, let me know.

**Comment by rafaell-lycan** [comment]
@oscarmcm I make a setup in jekyll and I'll make a PR for the project.

Something about the technologies:
- Bower for packages;
- Grunt for tasks;
- Vanilla JS (I really don't like CoffeeScript);
- Pure CSS, no pre-processor to do that.

Currently I thinking if need make this on Jekyll, for now I make some HTML;

**Comment by oscarmcm** [comment]
@rafaell-lycan perfect, let me know when you do the PR for the project to clone the repository and so begin to help.

Maybe at this moment, I think that we only use HTML, but in a future, I believe that is necessary move this to Jekyll.

**Comment by rafaell-lycan** [comment]
@tadeuzagallo create a branch called gh-pages please.

Att,

**Comment by rafaell-lycan** [comment]
You can see the landing page [here](http://rafaell.cc/GithubPulse/) or the source [here](https://github.com/rafaell-lycan/GithubPulse/tree/gh-pages)

**Comment by oscarmcm** [comment]
@rafaell-lycan Nice, the simple html looks good :+1:

**Comment by GiaoGiaoCat** [comment]
@rafaell-lycan It is neat! . :+1:

**Comment by rafaell-lycan** [comment]
@oscarmcm I'm almost drunk now, the only way to have extra creativity :P

I'm not as good as the designer @wjp2013 haha

@wjp2013 if you can, send me some images of the application in your new layout? Like in the "What" section.

**Comment by oscarmcm** [comment]
@rafaell-lycan maybe we can add fancy animations to the site :wink:

**Comment by GiaoGiaoCat** [comment]
@rafaell-lycan With pleasure. I am chinese and It's time for me to go to bed. I will focus on these images when i wake up. :laughing:

**Comment by rafaell-lycan** [comment]
@wjp2013 I'm brazilian, and I went to sleep after 3am :P

**Comment by GiaoGiaoCat** [comment]
![artboard2](https://cloud.githubusercontent.com/assets/173622/5796530/8977d4ce-9fe4-11e4-8fa4-dcaf257c5a22.png)
![artboard3](https://cloud.githubusercontent.com/assets/173622/5796531/89ae9aae-9fe4-11e4-849d-92af6e056ba1.png)

sketch file: https://dl.dropboxusercontent.com/u/244623/github%20pulse.sketch

**Comment by rafaell-lycan** [comment]
Thanks @wjp2013 , You can send me the login page too? =)

**Comment by tadeuzagallo** [comment]
Just one comment, I think it should include the icon and the arrow on the `What is GithubPulse?` section for it to make sense.

**Comment by rafaell-lycan** [comment]
Why?

**Comment by tadeuzagallo** [comment]
Because the icon is the center of the project... It's the icon that alerts you that you haven't commited

**Comment by rafaell-lycan** [comment]
@wjp2013 send me the first image please?

http://rafaell.cc/GithubPulse/

@tadeuzagallo explain me later about the icon alerts, etc.

**Comment by GiaoGiaoCat** [comment]
@rafaell-lycan 

![artboard 3](https://cloud.githubusercontent.com/assets/173622/5871761/1d41bc98-a31d-11e4-9417-eac2036bc9ed.png)

**Comment by tadeuzagallo** [comment]
The page is already online on [tadeuzagallo.com/GithubPulse](http://tadeuzagallo.com/GithubPulse)

Thank you all! :D
