### ISSUE TITLE
redesign

### ISSUE THREAD

**Issue by GiaoGiaoCat** [tadeuzagallo/GithubPulse#21]
![artboard01](https://cloud.githubusercontent.com/assets/173622/5772966/6eda5628-9d96-11e4-9b26-21d20f8dedcf.png)
![artboard02](https://cloud.githubusercontent.com/assets/173622/5772967/6f0050da-9d96-11e4-845e-ab436e92e2e9.png)

Anybody like my design? here is the .sketch file https://dl.dropboxusercontent.com/u/244623/github%20pulse.sketch

Hope someone can pull a request to make the design to css and html. Sorry, i am not familiar with css.

fonts:
- [Montserrat](http://www.google.com/fonts/specimen/Montserrat) 
- [Open Sans font](https://www.google.com/fonts/specimen/Open+Sans)

**Comment by tadeuzagallo** [comment]
Wow, very nice! Thanks!
If nobody's done it so far I'll push it myself later today!

**Comment by rafaell-lycan** [comment]
@wjp2013 I draw something yesterday too.

**Comment by tadeuzagallo** [comment]
I released it on the [experimental branch](https://github.com/tadeuzagallo/GithubPulse/tree/experimental/dist), if you guys wan't to check it out first.

**Comment by GiaoGiaoCat** [comment]
cool :+1:
