### ISSUE TITLE
Add a creative commons license.

### ISSUE THREAD

**Issue by rafaell-lycan** [tadeuzagallo/GithubPulse#26]
Add a creative commons license.

Select one on http://creativecommons.org/

**Comment by rafaell-lycan** [comment]
@tadeuzagallo ?

**Comment by octalmage** [comment]
Why would he add a creative common license? The project is under the MIT license. 

https://github.com/tadeuzagallo/GithubPulse/blob/master/LICENSE

**Comment by rafaell-lycan** [comment]
You're right @octalmage . I'll close this issue.
