### ISSUE TITLE
List of users being followed

### ISSUE THREAD

**Issue by johnknaack** [tadeuzagallo/GithubPulse#31]
I created a list of the users you are following. It shows their commits today and current streak. This is something I wanted to use to help keep track of my team and push them to make public commits before they leave the office.

![following_list](https://cloud.githubusercontent.com/assets/1598370/5923655/0d32be20-a60a-11e4-8b86-4c0d668494a5.gif)

I still have some clean up work for things like pagination for > 100 users and firefox extension support before I do a pull request but I wanted to see if anyone had any feedback on it's current layout or improvements I could add. You can see the current branch [here](https://github.com/johnknaack/GithubPulse/tree/following-list).

**Comment by rafaell-lycan** [comment]
@johnknaack can I improve this design? Or maybe work with @wjp2013 to make a new visual for this?

Nice job.

**Comment by johnknaack** [comment]
Sure thing. The last thing I would consider myself is a designer. Let me know if there is anything I can provide.

**Comment by tadeuzagallo** [comment]
Wow, that looks nice!
I don't think the layout is bad, but if they can improve it, even better!

The only problem with the pagination is that we won't be able to sort... I don't what's the best solution... Maybe load them all at the first load, cache it, and update just the visible ones later, on demand.

About the code, I'm glad you could understand my very hacky `Utils` file! hahaha
I just think you could use [`classSet`](http://facebook.github.io/react/docs/class-name-manipulation.html) on `UserLine`, and I don't know if we should include `async` right now... I don't like to use to many dependencies, the `Utils` file already implements a queue itself, and it really should be parallel... we just have to store the callbacks more like `Utils.get` and it should be good to go!

Thanks for contributing and happy coding! :smiley:

**Comment by johnknaack** [comment]
Awesome, I'll work on making those changes tonight.

**Comment by GiaoGiaoCat** [comment]
@rafaell-lycan I think the UI is good enough, i like it.

**Comment by johnknaack** [comment]
Ok, removed the async dependency, changed `UserLine` to use `classSet`, pulled full set of users instead of pagination, and added chrome extension support.

Let me know if you see anything that should be changed/updated.

**Comment by tadeuzagallo** [comment]
I'm closing it here since #32 has already been merged and will be release on the next version.
