### ISSUE TITLE
Retina menubar icon?

### ISSUE THREAD

**Issue by andypiper** [tadeuzagallo/GithubPulse#4]
The menubar icon looks fuzzy on my Retina MBP... :disappointed:

**Comment by tadeuzagallo** [comment]
Hey, thanks for pointing out! I really forgot that, I'll sheep it later today yet and I let you know!

**Comment by tadeuzagallo** [comment]
I just submitted a new version, it'd be great if you'd let me know if it worked later, because I don't have a rMBP to test it...
Thanks for contributing!

**Comment by andypiper** [comment]
Looks great! thanks! :smile:
