### ISSUE TITLE
Timezone support

### ISSUE THREAD

**Issue by relekang** [tadeuzagallo/GithubPulse#40]
Every morning GithubPulse will show commits from the last day. (I am in Central European Time)

**Comment by rafaell-lycan** [comment]
@tadeuzagallo we can use moment.js? Or the app gets the time from user computer?

**Comment by tadeuzagallo** [comment]
I don't think it's possible, it's how Github works... If you login on Github at that time you'll probably see the same...
Anyway, if you commit at some time, like in the morning, while your stats are still on the last day, it'll update and show the commit on the current day.

**Comment by relekang** [comment]
I understand, anyways thanks for looking into it :)
