### ISSUE TITLE
Reduce icon size. 

### ISSUE THREAD

**Issue by octalmage** [tadeuzagallo/GithubPulse#46]
Love the app! Got a new Macbook and it's working for me (#22). 

While it wasn't working I made my own version of the app, and I found that making the icon 20x20px matches the style of other icons:

![](https://cloudup.com/i5Y_x26AQRg+)
My app on is the right. 

Just a suggestion!

**Comment by tadeuzagallo** [comment]
(sorry for the delay)

I tried it when I was drawing the logo, but it seemed kinda hard to see what the logo actually was, but feel free to send a PR if you want to, and I can try it.

**Comment by rafaell-lycan** [comment]
@octalmage I haven't this problem. Looks good to me.

<img width="181" alt="screen shot 2016-05-05 at 11 03 30 am" src="https://cloud.githubusercontent.com/assets/1516450/15045475/0a46db28-12b1-11e6-8ccc-c772246474b7.png">

@tadeuzagallo if is it really necessary I could do it.

**Comment by octalmage** [comment]
Yeah I think it just looked small next to the other icons. It may be slightly bigger, but it's fine! 20x20 is really small. I'm going to close this! Keep up the great work.
