### ISSUE TITLE
Crash after username entry

### ISSUE THREAD

**Issue by kiliankoe** [tadeuzagallo/GithubPulse#5]
Hi, love the app idea!

Unfortunately I'm getting a crash right after entering my username. I've attached a crash report from Console.app on Hastebin (it's prettier than pastebin^^).

http://hastebin.com/nexexeqixo.pl

**Comment by tadeuzagallo** [comment]
Hey, thank you so much for reporting, just released a fix on [v0.2.6](https://github.com/tadeuzagallo/GithubPulse/releases/tag/v0.2.6)

**Comment by kiliankoe** [comment]
That was probably the fastest fix ever! Awesome!
