### ISSUE TITLE
Streaks no longer show up on the OS X menu app

### ISSUE THREAD

**Issue by sivakumar-kailasam** [tadeuzagallo/GithubPulse#53]
I had tried with multiple users' profiles but it still seems broken. The chart does show the last 7 days' stats but not the streak.

<img width="404" alt="screenshot 2017-03-26 12 29 51" src="https://cloud.githubusercontent.com/assets/604117/24329303/efe5ee62-121f-11e7-9c7e-f76c39bd3ee0.png">

**Comment by denizaygundev** [comment]
@tadeuzagallo 

I am also experiencing this issue and although it seems that development for this app has stopped it would be great to see the app continued.

![image](https://user-images.githubusercontent.com/7983695/44458572-997a3780-a5fe-11e8-9d9c-b19d17c7b6b1.png)
