### ISSUE TITLE
Support for a dark menubar?

### ISSUE THREAD

**Issue by kiliankoe** [tadeuzagallo/GithubPulse#6]
Would it be possible to add a light icon for people using the dark menubar in Yosemite? It's currently rather hard to see ;)

![screen shot 2015-01-13 at 16 27 01](https://cloud.githubusercontent.com/assets/2625584/5723004/1565c502-9b41-11e4-9a7d-407e911fb5e7.png)

Otherwise, as previously stated in the other issue: Absolutely love the idea for this! :D

**Comment by tadeuzagallo** [comment]
Hey thanks again for the report and for the compliment!
Just released [v0.2.7](https://github.com/tadeuzagallo/GithubPulse/releases/tag/v0.2.7) with dark icons support! please let me know if it looks okay to you! :D

**Comment by kiliankoe** [comment]
Looks fantastic, thank you very much! And you close issues far too fast :D
